document.addEventListener('DOMContentLoaded', () => {
    const container = document.getElementById('publications-container');

    // Fetch the JSON data generated by your Python script
    fetch('publications.json')
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response failed.');
            }
            return response.json();
        })
        .then(data => {
            // Clear the loading message
            container.innerHTML = ''; 

            if (data.length === 0) {
                container.innerHTML = '<p>No publications found.</p>';
                return;
            }

            // Loop through each publication and create HTML elements
            data.forEach(pub => {
                const pubElement = document.createElement('article');
                pubElement.className = 'publication-item';

                pubElement.innerHTML = `
                    <h3 class="pub-title"><a href="${pub.link}" target="_blank">${pub.title}</a></h3>
                    <div class="pub-meta">
                        <span class="pub-year">Year: ${pub.year}</span>
                        <span class="pub-citations">Cited by: ${pub.citations}</span>
                    </div>
                `;
                container.appendChild(pubElement);
            });
        })
        .catch(error => {
            console.error('Error fetching publications:', error);
            container.innerHTML = '<p>Sorry, could not load publications at this time.</p>';
        });
});