# .github/workflows/scholar_update.yml

name: Update Google Scholar Publications

# Controls when the action will run
# Runs on a schedule (at 05:30 UTC every day) and also allows manual runs
on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *' # Runs daily at 5:30 AM UTC

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-pubs:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu

    steps:
      # 1. Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Sets up a Python environment for your script
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # You can change this to your preferred Python version

      # 3. Installs the necessary Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scholarly

      # 4. Runs your Python script to fetch data and create publications.json
      - name: Run Python script to fetch publications
        run: python get_publications.py

      # 5. Commits the updated publications.json file back to your repository
      - name: Commit and push if there are changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add publications.json
          # Check for changes and commit only if there are any
          git diff --staged --quiet || git commit -m "Automated update of publications.json"
          git push